const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    PURCHASE_HISTORY_START: 'PURCHASE_HISTORY_START',
    PURCHASE_HISTORY_SUCCESS: 'PURCHASE_HISTORY_SUCCESS',
    PURCHASE_HISTORY_FAILURE: 'PURCHASE_HISTORY_FAILURE',
    FETCH_USERS_PURCHASE_START: 'FETCH_USERS_PURCHASE_START',
    FETCH_USERS_PURCHASE_SUCCESS: 'FETCH_USERS_PURCHASE_SUCCESS',
    FETCH_USERS_PURCHASE_FAILURE: 'FETCH_USERS_PURCHASE_FAILURE'
};

export default ShopActionTypes;